name: Build

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install RX3-Creator
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y python3 python3-pip vim-common
          git clone https://github.com/pawliczka/CRX3-Creator.git /tmp/CRX3-Creator
          sudo pip3 install -r /tmp/CRX3-Creator/requirements.txt

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build 115
        run: pnpm build

      - name: Write pem to file
        run: |
          echo "$CHROME_PEM" > /tmp/chrome.pem
        env:
          CHROME_PEM: ${{ secrets.CHROME_PEM }}

      - name: Package 115
        run: |
          python3 /tmp/CRX3-Creator/main.py -o 115.crx -pem /tmp/chrome.pem dist
          rm -rf release
          mv dist release
          mv 115.crx release

      - uses: EndBug/add-and-commit@v9
        with:
          add: "release"
          message: "[ci skip] update crx and release"
